### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by ykal** [Rajat421/react-native-sms-retriever-api#2]
When I tried to integrate to my project I got this error.
```
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-native-sms-retriever-api.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-sms-retriever-api: None of the consumable configurations have attributes.
```
React native version 0.55.3

**Comment by Rajat421** [comment]
Make sure you followed all the steps. try linking using manual steps.
you can also checkout my article on medium :-  https://medium.com/groww-engineering/google-sms-retriever-api-integration-with-react-native-fab31947f438
